// <auto-generated />
using System;
using InvenTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvenTrackFinalProject.Data.Migrations.InvenTrack
{
    [DbContext(typeof(InvenTrackContext))]
    [Migration("20260325200022_ReconcileChatNotifications")]
    partial class ReconcileChatNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvenTrack.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("InvenTrack.Models.ChatConversation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGroupChat")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("ID");

                    b.ToTable("ChatConversations");
                });

            modelBuilder.Entity("InvenTrack.Models.ChatConversationMember", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChatConversationID")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ChatConversationID", "UserId")
                        .IsUnique();

                    b.ToTable("ChatConversationMembers");
                });

            modelBuilder.Entity("InvenTrack.Models.ChatMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ChatConversationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("bit");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ChatConversationID");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("InvenTrack.Models.InventoryItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StorageLocationID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("StorageLocationID");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("InvenTrack.Models.InventoryItemStock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("StorageLocationID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StorageLocationID");

                    b.HasIndex("InventoryItemID", "StorageLocationID")
                        .IsUnique();

                    b.ToTable("InventoryItemStocks");
                });

            modelBuilder.Entity("InvenTrack.Models.ItemPhoto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("InventoryItemID")
                        .IsUnique();

                    b.ToTable("ItemPhotos");
                });

            modelBuilder.Entity("InvenTrack.Models.ItemThumbnail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("InventoryItemID")
                        .IsUnique();

                    b.ToTable("ItemThumbnails");
                });

            modelBuilder.Entity("InvenTrack.Models.StockTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromStorageLocationID")
                        .HasColumnType("int");

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ToStorageLocationID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FromStorageLocationID");

                    b.HasIndex("InventoryItemID");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasFilter("[ReferenceNumber] IS NOT NULL");

                    b.HasIndex("ToStorageLocationID");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("InvenTrack.Models.StockTransferRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReviewed")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromStorageLocationID")
                        .HasColumnType("int");

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RequestedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewedByName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ReviewedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ToStorageLocationID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FromStorageLocationID");

                    b.HasIndex("InventoryItemID");

                    b.HasIndex("ToStorageLocationID");

                    b.ToTable("StockTransferRequests");
                });

            modelBuilder.Entity("InvenTrack.Models.StorageLocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Building")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Room")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID");

                    b.ToTable("StorageLocations");
                });

            modelBuilder.Entity("InvenTrack.Models.ChatConversationMember", b =>
                {
                    b.HasOne("InvenTrack.Models.ChatConversation", "ChatConversation")
                        .WithMany("Members")
                        .HasForeignKey("ChatConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatConversation");
                });

            modelBuilder.Entity("InvenTrack.Models.ChatMessage", b =>
                {
                    b.HasOne("InvenTrack.Models.ChatConversation", "ChatConversation")
                        .WithMany("Messages")
                        .HasForeignKey("ChatConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatConversation");
                });

            modelBuilder.Entity("InvenTrack.Models.InventoryItem", b =>
                {
                    b.HasOne("InvenTrack.Models.Category", "Category")
                        .WithMany("InventoryItems")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvenTrack.Models.StorageLocation", "StorageLocation")
                        .WithMany("InventoryItems")
                        .HasForeignKey("StorageLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("InvenTrack.Models.InventoryItemStock", b =>
                {
                    b.HasOne("InvenTrack.Models.InventoryItem", "InventoryItem")
                        .WithMany("InventoryItemStocks")
                        .HasForeignKey("InventoryItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvenTrack.Models.StorageLocation", "StorageLocation")
                        .WithMany("InventoryItemStocks")
                        .HasForeignKey("StorageLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("InvenTrack.Models.ItemPhoto", b =>
                {
                    b.HasOne("InvenTrack.Models.InventoryItem", "InventoryItem")
                        .WithOne("ItemPhoto")
                        .HasForeignKey("InvenTrack.Models.ItemPhoto", "InventoryItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("InvenTrack.Models.ItemThumbnail", b =>
                {
                    b.HasOne("InvenTrack.Models.InventoryItem", "InventoryItem")
                        .WithOne("ItemThumbnail")
                        .HasForeignKey("InvenTrack.Models.ItemThumbnail", "InventoryItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("InvenTrack.Models.StockTransaction", b =>
                {
                    b.HasOne("InvenTrack.Models.StorageLocation", "FromStorageLocation")
                        .WithMany("FromStockTransactions")
                        .HasForeignKey("FromStorageLocationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvenTrack.Models.InventoryItem", "InventoryItem")
                        .WithMany("StockTransactions")
                        .HasForeignKey("InventoryItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvenTrack.Models.StorageLocation", "ToStorageLocation")
                        .WithMany("ToStockTransactions")
                        .HasForeignKey("ToStorageLocationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromStorageLocation");

                    b.Navigation("InventoryItem");

                    b.Navigation("ToStorageLocation");
                });

            modelBuilder.Entity("InvenTrack.Models.StockTransferRequest", b =>
                {
                    b.HasOne("InvenTrack.Models.StorageLocation", "FromStorageLocation")
                        .WithMany("TransferRequestsFromHere")
                        .HasForeignKey("FromStorageLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvenTrack.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvenTrack.Models.StorageLocation", "ToStorageLocation")
                        .WithMany("TransferRequestsToHere")
                        .HasForeignKey("ToStorageLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStorageLocation");

                    b.Navigation("InventoryItem");

                    b.Navigation("ToStorageLocation");
                });

            modelBuilder.Entity("InvenTrack.Models.Category", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("InvenTrack.Models.ChatConversation", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("InvenTrack.Models.InventoryItem", b =>
                {
                    b.Navigation("InventoryItemStocks");

                    b.Navigation("ItemPhoto");

                    b.Navigation("ItemThumbnail");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("InvenTrack.Models.StorageLocation", b =>
                {
                    b.Navigation("FromStockTransactions");

                    b.Navigation("InventoryItemStocks");

                    b.Navigation("InventoryItems");

                    b.Navigation("ToStockTransactions");

                    b.Navigation("TransferRequestsFromHere");

                    b.Navigation("TransferRequestsToHere");
                });
#pragma warning restore 612, 618
        }
    }
}
